version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    ports: [ "7080:8080" ]
    volumes: [ "jenkins_home:/var/jenkins_home" ]

  gitbucket:
    image: gitbucket/gitbucket
    ports: [ "7090:8080" ]
    volumes: [ "gitbucket_home:/gitbucket" ]

volumes:
  jenkins_home:
  gitbucket_home:

