version: '3'

services:

  registry:
    image: registry:2

  authproxy:
    image: nginx
    depends_on: [ registry ]
    ports: [ "5000:80" ]
    volumes:
      - "./htpasswd:/etc/htpasswd"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
