services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:9080'
        gitlab_rails['gitlab_shell_ssh_port'] = 9022
    ports:
      - "9080:9080"
      - "9443:443"
      - "9022:22"
    volumes:
      - data:/var/opt/gitlab
      - logs:/var/log/gitlab
      - config:/etc/gitlab
    shm_size: 256m

  runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  config:
  logs:
  data:
  runner-config:

