resources:
  - name: source
    type: git
    source:
      uri: https://github.com/backpaper0/spring-graphql-introduction.git

jobs:
  - name: test
    plan:
      - get: source
        trigger: true
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: bellsoft/liberica-openjdk-debian
              tag: 17
          inputs:
            - name: source
          caches:
            - path: m2
          run:
            path: bash
            args:
              - -c
              - |-
                set -eux
                cd source
                ./mvnw -B -ntp -Dmaven.repo.local=../m2 verify
